title:              Look and Love
email:             vuquangnguyen2019@yahoo.com
description:        Chia sẻ những hình ảnh thú vị về cuộc sống qua Nhiếp ảnh
author:             Lê Quang Photos
baseurl:            "/LookandLove"
url:                "https://vuquangnguyen2016.github.io"

# Social Profiles
twitter_username:   LeQuangHCMUS
github_username:    vuquangnguyen2016
facebook_username:  lequangvietnam
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
